### ISSUE TITLE
Connecting the MCP2515 to ECO_BUS Logomatic

### ISSUE THREAD

**Issue by alesha76** [flyingflo/heat_can#1]
Question how did you connect the MCP2515 pins (H) and (L) to the ECO_BUS Logomatic connector (1, 2, 3) there are (2) and (3) involved.

**Comment by flyingflo** [comment]
I don't remember exactly. 1 is the ground/shield. Just measure the voltage on the terminals, the higher voltage is CAN_HI, the lower CAN_LO. But hold on a second, MCP2515 is the CAN controller, there must be an CAN transceiver between it and the bus lines.

**Comment by alesha76** [comment]
By Logamatic it is clear. It turns out that in addition to NodeMCU and the MCP2515 board, there should be a transceiver? Is this another shield ? It is a pity that there is no schema in the Wiki.

**Comment by flyingflo** [comment]
There should be a tranceiver on the CAN board/shield. Otherwise, it
wouldn't be usable..
