### ISSUE TITLE
Question: GPIO pions

### ISSUE THREAD

**Issue by klemens-st** [flyingflo/heat_can#3]
Could you please explain where, in your setup, you have these two pins connected to?
https://github.com/flyingflo/heat_can/blob/bdbb7f5ef3ca848afef1269e6db69f8e5f94e427/src/main.cpp#L32-L33

From the code I understand what the purpose is, just not sure how the wiring works.

**Comment by flyingflo** [comment]
This requires tampering with the burner module of the controller. The pins are connected to signals on the PCB.
You only need those, if you want to control the burner behaviour.

- pin_lockout (out) disables the burner.
- pin_burning (in) reads the active LED.

I might have a photo, if you are curious. But be careful, damage is easily doable.

**Comment by klemens-st** [comment]
Thanks for the explanation. I think I will skip tampering with controller hardware for now as this feature is not something I really need but will remember to ask you for the photo if I change my mind!
