### ISSUE TITLE
How to get started with ESP32?

### ISSUE THREAD

**Issue by faspie** [flyingflo/heat_can#6]
Hi flo, 
I would like to get started with my ESP32 but I have no experience with that boards.
Are there precompiled firmware packages of your SW available?
What shall I do with your repository?
Thanks in advance!
Regards,
fabian

**Comment by flyingflo** [comment]
I recommend platform.io as toolchain. There are no precompiled firmwares. Anyways, configuration is part of the firmware, thus you will have make your own anyways.
